package com.stopmotion.app.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 baseline seed: #6750A4 (purple)
// Generated via Material Theme Builder.

// Light scheme
val md_primary_light = Color(0xFF6750A4)
val md_onPrimary_light = Color(0xFFFFFFFF)
val md_primaryContainer_light = Color(0xFFEADDFF)
val md_onPrimaryContainer_light = Color(0xFF21005D)
val md_secondary_light = Color(0xFF625B71)
val md_onSecondary_light = Color(0xFFFFFFFF)
val md_secondaryContainer_light = Color(0xFFE8DEF8)
val md_onSecondaryContainer_light = Color(0xFF1D192B)
val md_tertiary_light = Color(0xFF7D5260)
val md_onTertiary_light = Color(0xFFFFFFFF)
val md_tertiaryContainer_light = Color(0xFFFFD8E4)
val md_onTertiaryContainer_light = Color(0xFF31111D)
val md_error_light = Color(0xFFB3261E)
val md_onError_light = Color(0xFFFFFFFF)
val md_errorContainer_light = Color(0xFFF9DEDC)
val md_onErrorContainer_light = Color(0xFF410E0B)
val md_background_light = Color(0xFFFFFBFE)
val md_onBackground_light = Color(0xFF1C1B1F)
val md_surface_light = Color(0xFFFFFBFE)
val md_onSurface_light = Color(0xFF1C1B1F)
val md_surfaceVariant_light = Color(0xFFE7E0EC)
val md_onSurfaceVariant_light = Color(0xFF49454F)
val md_outline_light = Color(0xFF79747E)

// Dark scheme
val md_primary_dark = Color(0xFFD0BCFF)
val md_onPrimary_dark = Color(0xFF381E72)
val md_primaryContainer_dark = Color(0xFF4F378B)
val md_onPrimaryContainer_dark = Color(0xFFEADDFF)
val md_secondary_dark = Color(0xFFCCC2DC)
val md_onSecondary_dark = Color(0xFF332D41)
val md_secondaryContainer_dark = Color(0xFF4A4458)
val md_onSecondaryContainer_dark = Color(0xFFE8DEF8)
val md_tertiary_dark = Color(0xFFEFB8C8)
val md_onTertiary_dark = Color(0xFF492532)
val md_tertiaryContainer_dark = Color(0xFF633B48)
val md_onTertiaryContainer_dark = Color(0xFFFFD8E4)
val md_error_dark = Color(0xFFF2B8B5)
val md_onError_dark = Color(0xFF601410)
val md_errorContainer_dark = Color(0xFF8C1D18)
val md_onErrorContainer_dark = Color(0xFFF9DEDC)
val md_background_dark = Color(0xFF1C1B1F)
val md_onBackground_dark = Color(0xFFE6E1E5)
val md_surface_dark = Color(0xFF1C1B1F)
val md_onSurface_dark = Color(0xFFE6E1E5)
val md_surfaceVariant_dark = Color(0xFF49454F)
val md_onSurfaceVariant_dark = Color(0xFFCAC4D0)
val md_outline_dark = Color(0xFF938F99)
